### ISSUE TITLE
Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#28]
When making an API get method request, the following error occurs 

> Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
> at ServerResponse.setHeader (_http_outgoing.js:561:11)
> at ServerResponse.header (/app/node_modules/express/lib/response.js:771:10)
>  at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
>  at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
>  at /app/controllers/iol.js:12:14
> at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>  code: 'ERR_HTTP_HEADERS_SENT'
>  }

Seems related to when using `response.json` method to post the JSON to the server in response. May be related to sending responses twice. The data still goes to the database but useful to have the json response in the logs.

**Comment by medic-code** [comment]
Needed to add a return statement in the res.json if statement of the controller/iol.js
